# Example file to run RAC on a device with actualizr installed
[torizon]
url = "https://dgw.pilot.torizon.io/ras/"
server_cert_path = "/var/sota/import/root.crt"
client_cert_path = "/var/sota/import/client.pem"
client_key_path = "/var/sota/import/pkey.pem"

[device]
target_host_port = "127.0.0.1:22"
ssh_private_key_path = "/var/sota/import/device-key.sec"
authorized_keys_path = "/home/torizon/.ssh/authorized_keys2"
