[torizon]
url = "https://dgw.dev.torizon.io/ras"
server_cert_path = "/opt/rac/device-files/root.crt"
client_cert_path = "/opt/rac/device-files/client.pem"
client_key_path = "/opt/rac/device-files/pkey.pem"

[device]
ssh_host_port = "127.0.0.1:22"
ssh_private_key_path = "/opt/rac/device-files/device-key.sec"
ssh_public_key_path = "/opt/rac/device-files/device-key.pub"
authorized_keys_path = "/opt/rac/device-files/authorized-keys"
